# -*- coding: utf-8 -*-
"""
Created on Tue Sep 26 16:21:50 2023

@author: JoPHOBEA

This script manages the parallel framework of ERMESS
"""

from ERMESS_scripts.evolutionnary_core import ERMESS_evolutionnary_algorithm as EA
from ERMESS_scripts.evolutionnary_core import ERMESS_functions_research as Efr
from ERMESS_scripts.evolutionnary_core import ERMESS_functions_pro as Efp
from ERMESS_scripts.cost import ERMESS_cost_functions as Cfc
from multiprocessing import Pool

def init_and_evolution_pro(args_context):
    Context_initialisation_pro,Context = args_context
    pro_initial_population =  Efp.initial_population_pro(Context_initialisation_pro)
    pro_initial_solutions = EA.evolutionnary_algorithm_pro((Context_initialisation_pro,pro_initial_population))
    res_initial_solutions = Efr.pro_to_research(pro_initial_solutions, Context)
    nonjit_res_initial_solutions = Efr.unjitting_pop_res(res_initial_solutions)
    return(nonjit_res_initial_solutions)

def initial_population_research_PARALLEL(args_pop_init):
            """
            Generate the initial population (RESEARCH) in parallel using multiple processes.
            
            Each element in `args_pop_init` is passed to
            `fGA.initial_population_avec_pertes_contraintes_3`.
            
            Args:
                args_pop_init (list): List of argument tuples for each process call of the initial population generation function.
            
            Returns:
                list: List of populations generated in parallel.
            """
            pool = Pool()
            pop_init = pool.map(Efr.initial_population_research,args_pop_init)
            pool.close()
            pool.join()
            return(pop_init)       
        
def ere_evolutive_research_PARALLEL(args):
            """
            Runs the RESEARCH evolutionary algorithm in parallel.
            
            Each element in `args` is passed to `GA.genetic_algorithm_avec_pertes_contraintes_parallel2`.
            
            Args:
                args (list of tuple): List of argument tuples for each process call of the evolutionary algorithm.
                ere (object): Number of the current era in the global process.
                n_ere (int): Index or number of the ERE being processed.
            
            Returns:
                list: List of local populations generated by the evolutionary algorithm in parallel.
            """
            pool = Pool()
            local_populations=pool.map(EA.evolutionnary_algorithm_research, args)
            pool.close()
            pool.join()
            return(local_populations)

def ERMESS_pro_PARALLEL(args_pro):
            """
            Runs the PRO evolutionary algorithm in parallel.
            
            Each element in `args_pro` is passed to `GA.genetic_algorithm_pro`.
            
            Args:
                args_pro (list of tuple): List of argument tuples for each process call of the professional evolutionary algorithm.
            
            Returns:
                list: List of professional local populations generated in parallel.
                
            Note:
                Used only in the initialisation phase of the RESEARCH mode
            """
            pool = Pool()
            local_populations_pro=pool.map(init_and_evolution_pro, args_pro)
            pool.close()
            pool.join()
            return(local_populations_pro)
        
def parallel_fitness(args_fitness):
            """
            Computes fitness of populations in parallel.
            
            Each element in `args_fitness` is passed to `Cfc.fitness_list`.
            
            Args:
                args_fitness (list of tuple): List of argument tuples for each process call to compute fitness of individuals.
            
            Returns:
                list: List of fitness results for each population computed in parallel.
                
            Note:
                Used only in the initialisation phase of the RESEARCH mode
            """
            pool = Pool()
            local_populations=pool.map(Cfc.fitness_list, args_fitness)
            pool.close()
            pool.join()
            return(local_populations)
