# -*- coding: utf-8 -*-
"""
Created on Fri Jun 12 23:06:18 2026

@author: JoPHOBEA
"""

from ERMESS_scripts.load_model import ERMESS_Load_model as Elo
from pathlib import Path
import pickle as pkl
import pandas as pd

def load_test_case(case_name):
    """
    Load a predefined load-model test scenario from disk.

    The scenario is loaded from the corresponding directory under
    ``tests/scenarios/<case_name>`` and returned as a dictionary
    compatible with ``generate_microgrid_load(**scenario)``.

    Args:
        case_name (str):
            Name of the test scenario to load (e.g. ``"microgrid_1"``).

    Returns:
        dict:
            Dictionary containing all inputs required by
            ``generate_microgrid_load()``, including building data,
            flexibility settings, weather data, holidays, vacations,
            and time resolution.

    Raises:
        FileNotFoundError:
            If the specified scenario directory does not exist.
    """

    try:
        base_path = (Path(__file__).parent/ Path("tests/ERMESS_load_model")/ Path(case_name))
    except NameError:
        base_path = Path.cwd() / Path("tests/ERMESS_load_model") / Path(case_name)


    if not base_path.exists():
        raise FileNotFoundError(
            f"Case '{case_name}' not found : {base_path}"
        )

    with open(base_path / "building_list.pkl", "rb") as f:
        buildings = pkl.load(f)

    with open(base_path / "flexibility.pkl", "rb") as f:
        flexibility = pkl.load(f)

    with open(base_path / "meteo.pkl", "rb") as f:
        meteo = pkl.load(f)

    with open(base_path / "vacations.pkl", "rb") as f:
        vacations_raw = pkl.load(f)

    with open(base_path / "time_resolution.pkl", "rb") as f:
        time_resolution = pkl.load(f)

    if isinstance(meteo.columns, pd.MultiIndex):
        meteo.columns = meteo.columns.get_level_values(0)

    holidays = vacations_raw[0]
    vacation_starts = vacations_raw[1]
    vacation_ends = vacations_raw[2]

    vacations = pd.DataFrame({"vacation start dates": vacation_starts,"vacation end dates": vacation_ends,}).dropna(how="all")

    return {
        "building_list": buildings,
        "load_flexibility": flexibility,
        "meteoData": meteo,
        "holidays": holidays,
        "vacations": vacations,
        "time_resolution": time_resolution,
    }

   
def run_scenario(case_name, buildings):
    
    """Run a load-model validation scenario and return simulated and measured loads.

    This function prepares the building description file required by the
    load model, executes the load generation workflow for a given test case,
    and loads the corresponding measured data used for validation.
    
 
    Args:
        case_name (str):
            Name of the validation scenario. This name must correspond to
            a directory located in ``tests/ERMESS_load_model`` containing
            the scenario configuration and measured load data.
    
        buildings (pandas.DataFrame):
            Building description table used to generate the scenario load.
            Each row represents a building type and associated parameters
            (occupancy, thermal comfort settings, equipment, etc.).
            
    Returns:
        tuple[pandas.DataFrame, pandas.DataFrame]:
            A tuple containing:
    
            * simulated: simulated load profiles generated by
              ``Elo.generate_microgrid_load``.
            * measured: measured load profiles loaded from
              ``measured_load.pkl``.
    
    Raises:
        FileNotFoundError:
            If the scenario directory or required pickle files cannot
            be found.
    """
    
    building_list = pd.DataFrame(buildings)
    
    try:
        test_path = (Path(__file__).parent) / Path("tests/ERMESS_load_model") / Path(case_name)
    except NameError:
        test_path = Path.cwd() / Path("tests/ERMESS_load_model") / Path(case_name)
    
    with open(test_path / "building_list.pkl", "wb") as f:
        pkl.dump(building_list, f)

    scenario = load_test_case(f"{case_name}")
    simulated = Elo.generate_microgrid_load(**scenario)

    with open(test_path / "measured_load.pkl", "rb") as f:
        measured = pkl.load(f)

    return simulated, measured

#------------------------------------------------------------------
#ESIROI
#------------------------------------------------------------------

building_names = ['ESIROI_classes','ESIROI_labs']
building_types = ['teaching','lab']
building_numbers = [10,2]
building_pop = [20,6]
building_minT = [15,15]
building_maxT = [30,22]
building_base_load = ['Yes','Yes']
building_shared_equipment = ['Yes','Yes']
building_EV = ['Yes','No']
building_dhw = ['Yes','No']
building_IT = ['Yes','Yes']
building_light = ['Yes','Yes']
building_thermal = ['Yes','Yes']

building_list_ESIROI = pd.DataFrame((building_names,building_types,building_numbers,
                             building_pop,building_minT,
                             building_maxT,building_base_load,building_shared_equipment,
                             building_EV,building_dhw,building_IT,
                             building_light,building_thermal)).T

building_list_ESIROI.columns = ['Building','Type','Number','Number of users', 'Min. comfort temperature (°C)','Max. comfort temperature (°C)',
                         'Base load','Shared equipment','Electric vehicles','Domestic hot water','IT and office','Light','Thermal comfort']



#------------------------------------------------------------------
#IUT
#------------------------------------------------------------------

building_names = ['IUT_classes','IUT_labs']
building_types = ['teaching','lab']
building_numbers = [20,2]
building_pop = [20,6]
building_minT = [15,15]
building_maxT = [24,22]
building_base_load = ['Yes','Yes']
building_shared_equipment = ['Yes','Yes']
building_EV = ['Yes','No']
building_dhw = ['Yes','No']
building_IT = ['Yes','Yes']
building_light = ['Yes','Yes']
building_thermal = ['Yes','Yes']

building_list_IUT = pd.DataFrame((building_names,building_types,building_numbers,
                             building_pop,building_minT,
                             building_maxT,building_base_load,building_shared_equipment,
                             building_EV,building_dhw,building_IT,
                             building_light,building_thermal)).T

building_list_IUT.columns = ['Building','Type','Number','Number of users', 'Min. comfort temperature (°C)','Max. comfort temperature (°C)'
                         ,'Base load','Shared equipment','Electric vehicles','Domestic hot water','IT and office','Light','Thermal comfort']


#------------------------------------------------------------------
#ENERPOS
#------------------------------------------------------------------

building_names = ['ENERPOS']
building_types = ['office']
building_numbers = [4]
building_pop = [7]
building_minT = [15]
building_maxT = [30]
building_base_load = ['Yes']
building_shared_equipment = ['Yes']
building_EV = ['No']
building_dhw = ['Yes']
building_IT = ['Yes']
building_light = ['Yes']
building_thermal = ['Yes']

building_list_ENERPOS = pd.DataFrame((building_names,building_types,building_numbers,
                             building_pop,building_minT,
                             building_maxT,building_base_load,building_shared_equipment,
                             building_EV,building_dhw,building_IT,
                             building_light,building_thermal)).T

building_list_ENERPOS.columns = ['Building','Type','Number','Number of users', 'Min. comfort temperature (°C)','Max. comfort temperature (°C)'
                         ,'Base load','Shared equipment','Electric vehicles','Domestic hot water','IT and office','Light','Thermal comfort']


#------------------------------------------------------------------
#CROUS
#------------------------------------------------------------------

building_names = ['CROUS','restaurant']
building_types = ['dormitory','tertiary_food_service']
building_numbers = [1,1]
building_pop = [250,1000]
building_minT = [15,15]
building_maxT = [24,29]
building_base_load = ['Yes','Yes']
building_shared_equipment = ['Yes','Yes']
building_EV = ['No','No']
building_dhw = ['Yes','No']
building_IT = ['Yes','No']
building_light = ['Yes','Yes']
building_thermal = ['Yes','Yes']


building_list_CROUS = pd.DataFrame((building_names,building_types,building_numbers,
                             building_pop,building_minT,
                             building_maxT,building_base_load,building_shared_equipment,
                             building_EV,building_dhw,building_IT,
                             building_light,building_thermal)).T
building_list_CROUS.columns = ['Building','Type','Number','Number of users', 'Min. comfort temperature (°C)','Max. comfort temperature (°C)'
                         ,'Base load','Shared equipment','Electric vehicles','Domestic hot water','IT and office','Light','Thermal comfort']


if __name__ == "__main__":

    run_scenario("ESIROI_Terre_Sainte", building_list_ESIROI)
    run_scenario("IUT_Terre_Sainte", building_list_IUT)
    run_scenario("ENERPOS_Terre_Sainte", building_list_ENERPOS)
    run_scenario("CROUS_Terre_Sainte", building_list_CROUS)

